version: "3.4"
services:
  photoframe-client:
    build: "./"
    restart: unless-stopped
    ports:
      - 3000:3000
    # volumes:
    #   - ${PHOTOS_DIR}:/app/photos
  browser:
    image: balenablocks/browser
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
