version: "3.4"
services:
  photoframe-client:
    build: "./"
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ${PHOTOS_DIR}:/app/photos # If using local photos
  # wifi-connect:
  #   image: balenablocks/wifi-connect:amd64
  #   restart: always
  #   network_mode: host
  #   privileged: true
  #   labels:
  #     io.balena.features.dbus: "1"
  #     io.balena.features.firmware: "1"
